version: '3.8'
services:
  web:
    build: ./usr/src/app         # Directorio donde se encuentra tu aplicación Node.js
    ports:
      - "3000:3000"      # Mapeo de puerto de la aplicación Node.js
    depends_on:
      - db               # Dependencia del servicio de base de datos

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ubuntu5to
      MYSQL_DATABASE: bd_sistemapedidos
      MYSQL_USER: root
      MYSQL_PASSWORD: ubuntu5to
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"          # Puerto de Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Configuración de Nginx

volumes:
  db_data:
